name: tatrupiah_si
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  gap: ^3.0.1
  get_storage: ^2.1.1
  dio: ^5.4.3+1
  logger: ^2.2.0
  weekly_calendar: ^0.1.2
  lottie: ^3.1.0
  envied: ^0.5.4+1
  build_runner: ^2.4.9
  dash_chat_2: ^0.0.20
  chat_gpt_sdk: ^3.0.4

dependency_overrides:
  intl: ^0.18.0

dev_dependencies: 
  envied_generator: ^0.5.4+1
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets: 
    - assets/icons/
    - assets/images/
    - assets/animations/
    
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  uses-material-design: true